<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GUI_Test\GUI_Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Platform.Gtk" Version="2.10.2" />
  </ItemGroup>
	
</Project>
